# Form implementation generated from reading ui file 'D:\StudentManagement\Retail_Project\UI\LoginMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(570, 265)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(200, 30, 351, 151))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 43, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 51, 16))
        self.label_2.setObjectName("label_2")
        self.le_email = QtWidgets.QLineEdit(parent=self.groupBox)
        self.le_email.setGeometry(QtCore.QRect(50, 20, 271, 20))
        self.le_email.setObjectName("le_email")
        self.le_password = QtWidgets.QLineEdit(parent=self.groupBox)
        self.le_password.setGeometry(QtCore.QRect(60, 50, 261, 20))
        self.le_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.le_password.setObjectName("le_password")
        self.checkBox = QtWidgets.QCheckBox(parent=self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(10, 90, 121, 17))
        self.checkBox.setObjectName("checkBox")
        self.button_login = QtWidgets.QPushButton(parent=self.groupBox)
        self.button_login.setGeometry(QtCore.QRect(40, 120, 75, 23))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\StudentManagement\\Retail_Project\\UI\\../images/4115234_login_sign in_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.button_login.setIcon(icon)
        self.button_login.setObjectName("button_login")
        self.button_exit = QtWidgets.QPushButton(parent=self.groupBox)
        self.button_exit.setGeometry(QtCore.QRect(210, 120, 75, 23))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\StudentManagement\\Retail_Project\\UI\\../images/1564506_close_exit_logout_power_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.button_exit.setIcon(icon1)
        self.button_exit.setObjectName("button_exit")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 30, 151, 151))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("D:\\StudentManagement\\Retail_Project\\UI\\../images/5027870_admin_man_person_user_icon.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 570, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Login System:"))
        self.label.setText(_translate("MainWindow", "Email:"))
        self.label_2.setText(_translate("MainWindow", "Password:"))
        self.le_email.setText(_translate("MainWindow", "Omaba@gmail.com"))
        self.le_password.setText(_translate("MainWindow", "123"))
        self.checkBox.setText(_translate("MainWindow", "Save login information "))
        self.button_login.setText(_translate("MainWindow", "Login"))
        self.button_exit.setText(_translate("MainWindow", "Exit"))
